"""add monthly_snapshots table

Revision ID: 09d5243d085b
Revises: e35168718179
Create Date: 2026-06-13 15:34:02.109645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d5243d085b'
down_revision: Union[str, Sequence[str], None] = 'e35168718179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('total_brl', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('month_return_pct', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('cumulative_return_pct', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('income_month_brl', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_snapshots_year_month'), 'monthly_snapshots', ['year_month'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_snapshots_year_month'), table_name='monthly_snapshots')
    op.drop_table('monthly_snapshots')
    # ### end Alembic commands ###
