"""create transactions, quotes, exchange_rates

Revision ID: c2b63134dec0
Revises: 
Create Date: 2026-06-11 21:19:34.882939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b63134dec0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair', 'date', name='uq_exchange_rates_pair_date')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_ticker'), 'quotes', ['ticker'], unique=False)
    op.create_index('ix_quotes_ticker_fetched_at', 'quotes', ['ticker', 'fetched_at'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('cei', 'avenue', 'ibkr', 'binance', 'manual', name='source', native_enum=False, length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=40), nullable=False),
    sa.Column('asset_name', sa.String(length=200), nullable=True),
    sa.Column('asset_class', sa.Enum('stock', 'fii', 'etf', 'fixed_income', 'crypto', name='assetclass', native_enum=False, length=20), nullable=False),
    sa.Column('market', sa.Enum('br', 'us', 'crypto', name='market', native_enum=False, length=10), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('operation', sa.Enum('buy', 'sell', 'dividend', 'jcp', 'yield_', 'transfer', 'split', 'bonus', name='operation', native_enum=False, length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('fees', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('import_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_hash')
    )
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_ticker'), 'transactions', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_ticker'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_quotes_ticker_fetched_at', table_name='quotes')
    op.drop_index(op.f('ix_quotes_ticker'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
