"""add asset_meta table

Revision ID: e35168718179
Revises: e0ee1b737046
Create Date: 2026-06-12 21:07:25.414062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35168718179'
down_revision: Union[str, Sequence[str], None] = 'e0ee1b737046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_meta',
    sa.Column('ticker', sa.String(length=40), nullable=False),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_meta')
    # ### end Alembic commands ###
